'''
Zawiera funkcje odpowiedzialne za wyświetlanie
informacji w poszczególnych menu
'''

def bannerMain():
    print("================================")
    print("||                            ||")
    print("||       Diffie Hellman       ||")
    print("||                            ||")
    print("||          Algorithm         ||")
    print("||                            ||")
    print("================================")
    print("||                            ||")
    print("||          MAIN MENU         ||")
    print("||                            ||")
    print("================================")
    print("|       DOKONAJ WYBORU:        |")
    print("--------------------------------")
    print("| [1]   Wybierz liczbę A        |")
    print("--------------------------------")
    print("| [2]   Wczytaj wiadomość      |")
    print("--------------------------------")
    print("| [3]   Generuj wiadomość      |")
    print("--------------------------------")
    print("| [4]   Generuj klucz          |")
    print("--------------------------------")
    print("| [5]   Pokaż klucze           |")
    print("--------------------------------")
    print("| [6]   Wyślij klucz           |")
    print("--------------------------------")
    print("| [7]   ZAKOŃCZ                |")
    print("--------------------------------\n")

def bannerWybierzA():
    print("================================")
    print("||                            ||")
    print("||          WYBIERZ A         ||")
    print("||                            ||")
    print("================================")
    print("|       DOKONAJ WYBORU:        |")
    print("--------------------------------")
    print("| [1]   Podaj liczbę A         |")
    print("--------------------------------")
    print("| [2]   Generuj liczbę A       |")
    print("--------------------------------")
    print("| [3]   Wczytaj z pliku        |")
    print("--------------------------------")
    print("| [4]   Wróć do MENU           |")
    print("--------------------------------\n")

def bannerWczytajKlucz():
    print("================================")
    print("||                            ||")
    print("||       WCZYTAJ KLUCZ        ||")
    print("||                            ||")
    print("================================")
    print("|       DOKONAJ WYBORU:        |")
    print("--------------------------------")
    print("| [1]   Podaj klucz            |")
    print("--------------------------------")
    print("| [2]   Wczytaj z pliku        |")
    print("--------------------------------")
    print("| [3]   Wróć do menu           |")
    print("--------------------------------\n")

def bannerMenuZapis():
    print("================================")
    print("||                            ||")
    print("||           ZAPISZ           ||")
    print("||                            ||")
    print("================================")
    print("|       DOKONAJ WYBORU:        |")
    print("--------------------------------")
    print("| [1]   Zapisz do pliku        |")
    print("--------------------------------")
    print("| [2]   Wróć do MENU           |")
    print("--------------------------------\n")
